# Generated by Django 6.0.6 on 2026-07-27 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_area', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('departure_time_start', models.TimeField(blank=True, null=True)),
                ('departure_time_end', models.TimeField(blank=True, null=True)),
                ('days_active', models.CharField(default='Sun,Mon,Tue,Wed,Thu', help_text='Comma-separated days active, e.g. Sun,Mon,Tue,Wed,Thu', max_length=100)),
                ('transport_mode', models.CharField(blank=True, help_text='Preferred transport mode e.g. Rickshaw, Bus, Ride-share', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('gender_preference', models.CharField(choices=[('ANY', 'Any'), ('MALE_ONLY', 'Male Only'), ('FEMALE_ONLY', 'Female Only')], default='ANY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('contact_info', models.CharField(blank=True, help_text='Contact info unlocked only after a match request is accepted', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('requester_contact_info', models.CharField(blank=True, help_text='Contact details shared by requester once request is accepted', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_join_requests', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='route_mate.route')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('route', 'requester')},
            },
        ),
    ]
