# Generated by Django 6.0.6 on 2026-07-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_profile', '0002_facultyprofile_profile_photo_facultylink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('intake', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='faculty_profile.facultyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
