# Generated by Django 6.0.6 on 2026-08-17 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='lostfounditem',
            old_name='date_seen',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='lostfounditem',
            name='found_at',
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='item_type',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], db_index=True, default='LOST', max_length=5),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=10),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['status', 'item_type'], name='lost_found__status_193300_idx'),
        ),
        migrations.AddField(
            model_name='claimattempt',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimattempt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_attempts', to='lost_found.lostfounditem'),
        ),
        migrations.AddField(
            model_name='claimanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lost_found.claimattempt'),
        ),
        migrations.AddField(
            model_name='claimquestion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_questions', to='lost_found.lostfounditem'),
        ),
        migrations.AddField(
            model_name='claimanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.claimquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='claimattempt',
            unique_together={('item', 'claimant')},
        ),
    ]
