# Generated by Django 6.0.6 on 2026-07-23 04:12

from django.db import migrations, models


def backfill_titles(apps, schema_editor):
    """Existing notices predate the title field — derive one so old rows
    don't show up blank: the highlight label if set, else a text snippet."""
    Notice = apps.get_model('notices', 'Notice')
    for notice in Notice.objects.all():
        if notice.highlight:
            title = notice.highlight
        else:
            text = (notice.text or '').strip()
            title = text[:57] + '…' if len(text) > 60 else text
        notice.title = title or 'Notice'
        notice.save(update_fields=['title'])


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_event_date_notice_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(backfill_titles, migrations.RunPython.noop),
    ]
