# Generated by Django 6.0.6 on 2026-07-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'Slides'), ('DOC', 'Doc'), ('VID', 'Video')], max_length=3)),
                ('size_label', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='subjects.subject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
