# Generated by Django 6.0.6 on 2026-07-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='size_label',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='topic',
        ),
    ]
