# Generated by Django 6.0.6 on 2026-07-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_authors(apps, schema_editor):
    """Existing resources were posted by their subject's faculty owner."""
    Resource = apps.get_model('resources', 'Resource')
    for resource in Resource.objects.select_related('subject__faculty').all():
        resource.author_id = resource.subject.faculty.user_id
        resource.save(update_fields=['author'])


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_options_remove_resource_size_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_authors, migrations.RunPython.noop),
    ]
