# Generated by Django 6.0.6 on 2026-07-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='profile_photo',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='FacultyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='faculty_profile.facultyprofile')),
            ],
        ),
    ]
