# Generated by Django 6.0.6 on 2026-08-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('JOIN_REQUEST', 'Join request'), ('JOIN_REQUEST_RESPONSE', 'Join request response'), ('POST_FULL', 'Post full'), ('ROUTE_JOIN_REQUEST', 'Route join request'), ('ROUTE_JOIN_REQUEST_RESPONSE', 'Route join request response'), ('NOTICE_POSTED', 'Notice posted'), ('RESOURCE_POSTED', 'Resource posted'), ('FEED_POST', 'Feed post')], default='SYSTEM', max_length=30),
        ),
    ]
