# Generated by Django 6.0.6 on 2026-08-18 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_claimanswer_claimattempt_claimquestion_and_more'),
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='claim_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lost_found.claimattempt'),
        ),
        migrations.AddField(
            model_name='notification',
            name='lost_found_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lost_found.lostfounditem'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('JOIN_REQUEST', 'Join request'), ('JOIN_REQUEST_RESPONSE', 'Join request response'), ('POST_FULL', 'Post full'), ('ROUTE_JOIN_REQUEST', 'Route join request'), ('ROUTE_JOIN_REQUEST_RESPONSE', 'Route join request response'), ('NOTICE_POSTED', 'Notice posted'), ('RESOURCE_POSTED', 'Resource posted'), ('FEED_POST', 'Feed post'), ('CLAIM_REQUEST', 'Claim request'), ('CLAIM_REQUEST_RESPONSE', 'Claim request response')], default='SYSTEM', max_length=30),
        ),
    ]
